/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cylin' at '7/6/16 11:05 AM' with Gradle 2.11
 *
 * @author cylin, @date 7/6/16 11:05 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
